development:
  adapter: postgresql
  encoding: unicode
  database: milkrunner_development
  pool: 5
  username: milkman
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: milkrunner_test
  pool: 5
  username: milkman
  password:
  host: localhost
